version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - mvn -v

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.war
  discard-paths: no
